**Datos del estudiante**:
* Nombre: David Steven Santos Santos
* Código: 20152020076
* Proyecto Curricular: Ingeniería de Sistemas

# NumPY
## 1. Resumen
* **¿Qué hace la librería?**

Numpy es una librería de código abierto desarrollado por la comunidad su objetivo se basa en los arreglos multidimensionales, esto con la intención de mejorar las listas y tuplas que python ofrece, sus ventajas son la eficiencia en operaciones complejas en el uso de estos arreglos.

* **¿Qué usos se le da en el ambiente científico?**

Debido a que es una librería de computación científica, se puede aplicar en matemáticas en los temas como, álgebra lineal (matrices y vectores),Números complejos (transformadas de Fourier), Generacion de numeros pseudoaleatorios, con respecto a este tema se podría decir que sí es estadísticamente la generación de estos números muy buena, se podría implementar en criptografía.

* **Historia**

Al principio hubo la librería Numeric. Originalmente fue escrito en 1995 en gran parte por Jim Hugunin con la ayuda de muchas personas, entre ellas Jim Fulton, David Ascher, Paul DuBois y Konrad Hinsen. Desafortunadamente, Numeric adquirió varios apodos: Numerical Python, Numerical, NumPy. Por ejemplo, el nombre del proyecto de SourceForge es numpy, el antiguo módulo CVS es Numerical, Konrad Hinsen llamó a su paquete ScientificPython en referencia a Numerical Python. A principios de 2005, Travis Oliphant quería reunir a la comunidad en un solo paquete de arreglos. Adecuo el código de Numeric y lo hizo más robusto y flexible, a lo cual llevó a que creara el proyecto Scipy y consigo la consolidación de NumPy.

* **Describir 3 funciones/operaciones que no se hayan mencionado en la sesión presencial**

No asistí a la clase presencial pero me baso en el documento Sesión 2 de pygroup:
aprendiendo NumPy.

* Las operaciones con string: Este módulo proporciona un conjunto de operaciones de cadena vectorizadas para matrices de tipo numpy.string_ onumpy.unicode_. Todos ellos se basan en los métodos de cadena en la biblioteca estándar de Python. Como ejemplo se puede ver el siguiente método.
    * numpy.core.defchararray.encode. codifica un arreglo con respecto a una codificación estandár.
* Programación Funcional: esta librería soporta el paradigma de la programación funcional, una de sus funciones es.
    * numpy.frompyfunc : toma una función normal de python y la convierte en una función de NumPy ufunc.
* Polinomios: Los polinomios en NumPy se pueden crear, manipular e incluso ajustar. uno de sus métodos es.
    * hallar el dominio del polinomio con numpy.polinomial.domain


## 2. Ejercicios
1. Realizar los "Ejercicios Rápidos" que están en el Cuaderno de la sesión N° 2
http://aulas.aprendiendoaprogramar.com/file.php/75/Sesion_2_Pygroup.htm
1. Escriba un programa para crear un arreglo de dimensión 10x4 y extraiga las primeras 3 filas de ese arreglo y guardelas en una variable llamada slice 
1. Escriba un programa donde declare dos vectores (Arreglos unidimensionales) con valores aleatorios y luego use una función de la libreria para verificar si esos dos vectores son iguales.
1. Cree una matriz de 6x6 cuya diagonal sea [1,2,3,4,5,6] e imprima la matriz
1. nvestigue el método dot de la libreria Numpy y realice una multiplicación de matrices. La primera matriz debe ser de tamaño 5x3 y la otra matriz de 3x2

**Desarrollo**:
    1. Ejercicios Rápidos

In [12]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: David Steven Santos Santos
codigo: 20152020076
Ingenieria de sistemas
version: 3.7.3
"""
import numpy as np
print("*****************************************************************************************************************************")
print("EJERCICIOS NUMPY PRIMER PUNTO")
matrizPrueba = np.array([ [34,23,546,788],[12,1099,434,214],[1234,5454,6466,2323],[2332,657,896,53] ])
print("matriz: \n {}".format(matrizPrueba) )
#¿Cuál es el índice para el elemento 5454?
print("indice del elemento: \n {}".format(matrizPrueba[2,1]) )
#"Rebane" la matriz matrizPrueba de forma que seleccione las filas pares y todas sus columnas
print("filas pares y todas sus columnas: \n {}".format(matrizPrueba[0::2]) ) #start:stop:step considerando que se cuenta desde 0
matrizA = np.arange(12)
matrizB = np.arange(12)
print("matriz B: \n {}".format(matrizB) )
#Sacar la raíz cuadrada de los valores de la matriz B
print("Raiz cuadrada de la matrizB: \n {}".format(np.sqrt(matrizB).reshape((3,4))) )
#Cree una matriz de 4x4 y haga su transpuesta
matriz4b4 = np.empty((4, 4))
print("Matriz de 4x4: \n {}".format(matriz4b4))
print("Matriz transpuesta: \n {}".format(np.transpose(matriz4b4)) )

*****************************************************************************************************************************
EJERCICIOS NUMPY PRIMER PUNTO
matriz: 
 [[  34   23  546  788]
 [  12 1099  434  214]
 [1234 5454 6466 2323]
 [2332  657  896   53]]
indice del elemento: 
 5454
filas pares y todas sus columnas: 
 [[  34   23  546  788]
 [1234 5454 6466 2323]]
matriz B: 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raiz cuadrada de la matrizB: 
 [[0.         1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974 2.64575131]
 [2.82842712 3.         3.16227766 3.31662479]]
Matriz de 4x4: 
 [[1.6798e-322 1.1364e-322 2.6976e-321 3.8932e-321]
 [5.9288e-323 5.4298e-321 2.1442e-321 1.0573e-321]
 [6.0968e-321 2.6946e-320 3.1946e-320 1.1477e-320]
 [1.1522e-320 3.2460e-321 4.4268e-321 2.6185e-322]]
Matriz transpuesta: 
 [[1.6798e-322 5.9288e-323 6.0968e-321 1.1522e-320]
 [1.1364e-322 5.4298e-321 2.6946e-320 3.2460e-321]
 [2.6976e-321 2.1442e-321 3.1946e-320 4.4268e-321]
 [3.8932e-

    2. Segundo Punto

In [3]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: David Steven Santos Santos
codigo: 20152020076
Ingenieria de sistemas
version: 3.7.3
"""
import numpy as np
print("*****************************************************************************************************************************")
print("EJERCICIOS NUMPY SEGUNDO PUNTO")
#Escriba un programa para crear un arreglo de dimensión 10x4 y extraiga las primeras 3 filas de ese arreglo y guardelas en una variable llamada slice
matriz = np.empty((10, 4))
print("matriz 10x4: \n {}".format(matriz) )
sliceVar = matriz[0:3:]  #debido a que slice es una palabra reservada de python lo llamo sliceVar
print("slice: \n {}".format(sliceVar) )

*****************************************************************************************************************************
EJERCICIOS NUMPY SEGUNDO PUNTO
matriz 10x4: 
 [[2.14528411e-314 2.14605215e-314 2.14543514e-314 2.14538939e-314]
 [2.15009401e-314 2.14709665e-314 2.15323068e-314 2.14839877e-314]
 [2.17941363e-314 2.15129326e-314 2.14471625e-314 2.14528425e-314]
 [2.14542072e-314 2.14530532e-314 2.17937905e-314 2.14530543e-314]
 [2.14787358e-314 2.14541909e-314 2.14684493e-314 2.14528364e-314]
 [2.14541878e-314 2.14546902e-314 2.14471449e-314 2.17211043e-314]
 [2.14540159e-314 2.14530648e-314 2.14530651e-314 2.17941377e-314]
 [2.14607920e-314 2.14528383e-314 2.14541870e-314 2.14541845e-314]
 [2.14608502e-314 2.17937914e-314 2.14540179e-314 2.14548221e-314]
 [2.17937918e-314 2.14541862e-314 2.17937921e-314 2.17937924e-314]]
slice: 
 [[2.14528411e-314 2.14605215e-314 2.14543514e-314 2.14538939e-314]
 [2.15009401e-314 2.14709665e-314 2.15323068e-314 2.14839877e-314]
 [2.17941363e-

    3. Tercer Punto

In [5]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: David Steven Santos Santos
codigo: 20152020076
Ingenieria de sistemas
version: 3.7.3
"""
import numpy as np
print("*****************************************************************************************************************************")
print("EJERCICIOS NUMPY TERCER PUNTO")
#haga 2 arreglos unidimensionales con valores aleatorios y determinen si son iguales
vector1 = np.random.rand(15)
vector2 = np.random.rand(15)
print("Vector 1: \n {}".format(vector1) )
print("Vector 2: \n {}".format(vector2) )
print("son iguales: %s" %np.array_equal(vector1, vector2) )

*****************************************************************************************************************************
EJERCICIOS NUMPY TERCER PUNTO
Vector 1: 
 [0.81678825 0.62180314 0.68095548 0.88988669 0.98888572 0.65665788
 0.69089036 0.07208006 0.91380836 0.67403651 0.06479564 0.70434673
 0.36286875 0.72837761 0.63055056]
Vector 2: 
 [0.4278893  0.59551068 0.24694527 0.83554374 0.07249792 0.07669931
 0.08500272 0.96529517 0.74528793 0.33164283 0.57482586 0.9208082
 0.44466603 0.86577098 0.03948904]
son iguales: False


    4. Cuarto punto

In [6]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: David Steven Santos Santos
codigo: 20152020076
Ingenieria de sistemas
version: 3.7.3
"""
import numpy as np
print("*****************************************************************************************************************************")
print("EJERCICIOS NUMPY CUARTO PUNTO")
#cree una matriz 6x6 cuya diagonal sea [1,2,3,4,5,6] e imprima una matriz
diagonal = np.diagflat([[1, 2], [3, 4], [5, 6]])
print("matriz 6x6: \n {}".format(diagonal) )

*****************************************************************************************************************************
EJERCICIOS NUMPY CUARTO PUNTO
matriz 6x6: 
 [[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


    5. Quinto punto

In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
@author: David Steven Santos Santos
codigo: 20152020076
Ingenieria de sistemas
version: 3.7.3
"""
import numpy as np
print("*****************************************************************************************************************************")
print("EJERCICIOS NUMPY QUINTO PUNTO")
#realice una multiplicacion de matrices entre una matriz 5x3 y una matriz 3x2
m5x3 = np.random.rand(5, 3)
m3x2 = np.random.rand(3, 2)
print("matriz 5x3: \n {}".format(m5x3) )
print("matriz 3x2: \n {}".format(m3x2) )
dot = np.dot(m5x3,m3x2)
print("dot: \n {}".format(dot) )

*****************************************************************************************************************************
EJERCICIOS NUMPY QUINTO PUNTO
matriz 5x3: 
 [[0.75526215 0.54835422 0.76086983]
 [0.49601761 0.70343004 0.93556508]
 [0.63024897 0.58252416 0.32282289]
 [0.15505654 0.88400894 0.57901398]
 [0.5279608  0.4655825  0.9005502 ]]
matriz 3x2: 
 [[0.52971024 0.098775  ]
 [0.29117186 0.80128177]
 [0.94494312 0.28779334]]
dot: 
 [[1.27871413 0.73296053]
 [1.35162043 0.8818892 ]
 [0.80851324 0.62192511]
 [0.88666884 0.89029232]
 [1.26619947 0.68438444]]
